# Configuracion de log
logging:
  level:
    org:
      hibernate: ERROR
      springframework: INFO
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} {%thread} {%-5level} {%c{l}}: %msg%n'
server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never

# Configuracion de conexion a la BD
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: vtzlu2x2lbtefju2
    url: jdbc:mysql://eyw6324oty5fsovx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ypnce7psm1wg5ynu?useSSL=false
    password: g1ftkak877dgfqku
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

# Configuracion de seguridad
jwt:
  secret: secret
  expiration: 3600