# Configuracion de log
logging:
  level:
    org:
      hibernate: ERROR
      springframework: INFO
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} {%thread} {%-5level} {%c{l}}: %msg%n'
server:
  error:
    include-stacktrace: never

# Configuracion de conexion a la BD
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: b466047bb568fa
    url: jdbc:mysql://b466047bb568fa:8f75b3f4@us-cdbr-east-06.cleardb.net/heroku_e4e3cecd7d8c26a?reconnect=true
    password: 8f75b3f4
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

# Configuracion de seguridad
jwt:
  secret: secret
  expiration: 3600