# Configuracion de log
logging:
  level:
    org:
      hibernate: ERROR
      springframework: INFO
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} {%thread} {%-5level} {%c{l}}: %msg%n'
server:
  error:
    include-stacktrace: never

# Configuracion de conexion a la BD
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${USERNAME_JAWSDB}
    url: jdbc:${JAWSDB_URL}
    password: ${PASSWORD_JAWSDB}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

# Configuracion de seguridad
jwt:
  secret: secret
  expiration: 3600