# Configuracion de log
logging:
  level:
    org:
      hibernate: ERROR
      springframework: INFO
    root: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} {%thread} {%-5level} {%c{l}}: %msg%n'
server:
  error:
    include-stacktrace: never

# Configuracion de conexion a la BD
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: lue8l7ljl5qb2fpq
    url: jdbc:mysql://lue8l7ljl5qb2fpq:pefz93yh2zc5tamx@cis9cbtgerlk68wl.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/js504ij5r5k1x2fr
    password: pefz93yh2zc5tamx
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

# Configuracion de seguridad
jwt:
  secret: secret
  expiration: 3600